[package]
name = "pinger2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "pinger2"
crate-type = ["cdylib"]

[dependencies]
num-traits = "0.2.19"
pyo3 = "0.22.0"
sci-rs = "0.3.15"
