# See https://github.com/cra-ros-pkg/robot_localization/blob/humble-devel/params/ekf.yaml
ekf_filter_node:
  ros__parameters:
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
# accept vx, vy, vz
    odom0: sensors/dvl/odom
    odom0_config: [false, false, false,
                   false, false, false,
                   true,  true,  true,
                   false, false, false,
                   false, false, false]
# accept roll, pitch, yaw
    imu0: sensors/imu/imu
    imu0_config: [false, false, false,
                  true, true, true,
                  false, false, false,
                  false, false, false,
                  false, false, false]
