#ifndef THRUSTER_ALLOCATOR_H
#define THRUSTER_ALLOCATOR_H

#include <OsqpEigen/OsqpEigen.h>

#include <Eigen/Dense>
#include <string>

class ThrusterAllocator {
   private:
    /**
     * @brief Maximum absolute value allocation allowed for any thruster.
     */
    double max_alloc = 1.0;

    /**
     * @brief Wrench matrix.
     *
     * @details 6 x n matrix where n is the number of thrusters.
     * Each column represents the force and torque generated by a single thruster for each axis.
     * Each row represents an axis, in the order of x, y, z, roll, pitch, yaw from top to bottom.
     */
    Eigen::MatrixXd wrench;

    /**
     * @brief Pseudoinverse of wrench matrix.
     *
     * @details n x 6 matrix where n is the number of thrusters.
     */
    Eigen::MatrixXd wrench_pinv;

    /**
     * @brief OSQP solver.
     *
     * @details Solver for quadratic programming problems.
     */
    OsqpEigen::Solver solver;

    /**
     * @brief Get unconstrained thruster allocations for given set power by returning
     *  `wrench_pinv * set_power`.
     *
     * @param set_power Set power.
     * @param unconstrained_allocs Unconstrained thruster allocations.
     */
    void get_pseudoinverse_solution(const Eigen::VectorXd &set_power, Eigen::VectorXd &unconstrained_allocs);

    /**
     * @brief Get constrained thruster allocations for given set power using quadratic programming. This
     *  minimizes the norm of `set_power - wrench * constrained_allocs`.
     *
     * @param set_power Set power.
     * @param constrained_allocs Constrained thruster allocations.
     */
    void get_qp_solution(const Eigen::VectorXd &set_power, Eigen::VectorXd &constrained_allocs);

    /**
     * @brief Clip every component of `allocs` to the range [-max_alloc, max_alloc].
     *
     * @param allocs Thruster allocations to clip.
     */
    void clip_allocs(Eigen::VectorXd &allocs);

   public:
    /**
     * @brief Default constructor with empty `wrench` and `wrench_pinv`.
     */
    ThrusterAllocator();

    /**
     * @brief Constructor that reads `wrench` and `wrench_pinv` from CSV files.
     *
     * @param wrench_file_path Path to CSV file containing wrench matrix.
     * @param wrench_pinv_file_path Path to CSV file containing pseudoinverse of wrench matrix.
     */
    ThrusterAllocator(std::string wrench_file_path, std::string wrench_pinv_file_path);

    /**
     * @brief Allocates thruster power to achieve the provided set power.
     *
     * @param set_power Power to allocate to thrusters.
     * @param unconstrained_allocs Unconstrained thruster allocations (maximum absolute value allocation is unlimited).
     * @param constrained_allocs Constrained thruster allocations (maximum absolute value allocation is `max_alloc`).
     * @param actual_power Actual power delivered along each axis with `constrained_allocs`.
     * @param power_disparity Difference between `set_power` and `actual_power`.
     */
    void allocate_thrusters(const Eigen::VectorXd &set_power, Eigen::VectorXd &unconstrained_allocs,
                            Eigen::VectorXd &constrained_allocs, Eigen::VectorXd &actual_power,
                            Eigen::VectorXd &power_disparity);
};

#endif