pid:
  position:
    x:
      Kp: 4
      Ki: 0
      Kd: 5
      Ff: 0
      control_effort_limit: 1
      derivative_type: 0
      error_ramp_rate: 1000
    y:
      Kp: 3.5
      Ki: 0
      Kd: 5
      Ff: 0
      control_effort_limit: 1
      derivative_type: 0
      error_ramp_rate: 1000
    z:
      Kp: 2.9
      Ki: 0
      Kd: 3
      Ff: 0
      control_effort_limit: 1
      derivative_type: 0
      error_ramp_rate: 1000
    roll:
      Kp: 0.8
      Ki: 0
      Kd: 0.4
      Ff: 0
      control_effort_limit: 1
      derivative_type: 0
      error_ramp_rate: 1000
    pitch:
      Kp: 0.8
      Ki: 0
      Kd: 0.4
      Ff: 0
      control_effort_limit: 1
      derivative_type: 0
      error_ramp_rate: 1000
    yaw:
      Kp: 1
      Ki: 0
      Kd: 0.5
      Ff: 0
      control_effort_limit: 1
      derivative_type: 0
      error_ramp_rate: 1000
  position_cascaded:
    x:
      Kp: 4
      Ki: 0
      Kd: 5
      Ff: 0
      control_effort_limit: 1
      derivative_type: 0
      error_ramp_rate: 1000
    y:
      Kp: 3.5
      Ki: 0
      Kd: 5
      Ff: 0
      control_effort_limit: 1
      derivative_type: 0
      error_ramp_rate: 1000
    z:
      Kp: 2.9
      Ki: 0
      Kd: 3
      Ff: 0
      control_effort_limit: 1
      derivative_type: 0
      error_ramp_rate: 1000
    roll:
      Kp: 0.8
      Ki: 0
      Kd: 0.4
      Ff: 0
      control_effort_limit: 1
      derivative_type: 0
      error_ramp_rate: 1000
    pitch:
      Kp: 0.8
      Ki: 0
      Kd: 0.4
      Ff: 0
      control_effort_limit: 1
      derivative_type: 0
      error_ramp_rate: 1000
    yaw:
      Kp: 1
      Ki: 0
      Kd: 0.5
      Ff: 0
      control_effort_limit: 1
      derivative_type: 0
      error_ramp_rate: 1000
  velocity:
    x:
      Kp: 1.75
      Ki: 0.02
      Kd: 0.5
      Ff: 0
      control_effort_limit: 1
      derivative_type: 0
      error_ramp_rate: 1000
    y:
      Kp: 1
      Ki: 0.02
      Kd: 0.05
      Ff: 0
      control_effort_limit: 1
      derivative_type: 0
      error_ramp_rate: 1000
    z:
      Kp: 0.5
      Ki: 0.5
      Kd: 0.5
      Ff: 0
      control_effort_limit: 1
      derivative_type: 0
      error_ramp_rate: 1000
    roll:
      Kp: 0.01
      Ki: 0.001
      Kd: 0.01
      Ff: 0
      control_effort_limit: 1
      derivative_type: 0
      error_ramp_rate: 1000
    pitch:
      Kp: 0.1
      Ki: 0.001
      Kd: 0.01
      Ff: 0
      control_effort_limit: 1
      derivative_type: 0
      error_ramp_rate: 1000
    yaw:
      Kp: 0.01
      Ki: 0.001
      Kd: 0.01
      Ff: 0
      control_effort_limit: 1
      derivative_type: 0
      error_ramp_rate: 1000
static_power_global:
  x: 0
  y: 0
  z: -0.34
power_scale_factor: 1
thrusters:
  - name: bottom_front_left
    type: T200
    pos: [0.1905, 0.37465, -0.0381]
    rpy: [0, 90, 0]
    flipped: false
  - name: front_left
    type: T200
    pos: [0.3302, 0.358775, 0.0254]
    rpy: [0, 0, -45]
    flipped: true
  - name: front_right
    type: T200
    pos: [0.3302, -0.358775, 0.0254]
    rpy: [0, 0, 45]
    flipped: true
  - name: bottom_front_right
    type: T200
    pos: [0.1905, -0.37465, -0.0381]
    rpy: [0, 90, 0]
    flipped: false
  - name: bottom_back_left
    type: T200
    pos: [-0.1905, 0.37465, -0.0381]
    rpy: [0, 90, 0]
    flipped: false
  - name: back_left
    type: T200
    pos: [-0.3302, 0.358775, 0.0254]
    rpy: [0, 0, -135]
    flipped: true
  - name: bottom_back_right
    type: T200
    pos: [-0.1905, -0.37465, -0.0381]
    rpy: [0, 90, 0]
    flipped: false
  - name: back_right
    type: T200
    pos: [-0.3302, -0.358775, 0.0254]
    rpy: [0, 0, 135]
    flipped: true
wrench_matrix_file_path: data/oogway_wrench.csv
wrench_matrix_pinv_file_path: data/oogway_wrench_pinv.csv