pid:
  position:
    x:
      Kp: 3.8
      Ki: 0
      Kd: 1.5
      Ff: 0
    y:
      Kp: 5
      Ki: 0
      Kd: 2
      Ff: 0
    z:
      Kp: 2.9
      Ki: 0
      Kd: 2.6
      Ff: 0
    roll:
      Kp: 1
      Ki: 0
      Kd: 0
      Ff: 0
    pitch:
      Kp: 1
      Ki: 0
      Kd: 0
      Ff: 0
    yaw:
      Kp: 1
      Ki: 0
      Kd: 0.6
      Ff: 0
  velocity:
    x:
      Kp: 1.75
      Ki: 0.02
      Kd: 0.5
      Ff: 0
    y:
      Kp: 1
      Ki: 0.02
      Kd: 0.05
      Ff: 0
    z:
      Kp: 0.5
      Ki: 0.5
      Kd: 0.5
      Ff: 0
    roll:
      Kp: 0.01
      Ki: 0.001
      Kd: 0.01
      Ff: 0
    pitch:
      Kp: 0.1
      Ki: 0.001
      Kd: 0.01
      Ff: 0
    yaw:
      Kp: 0.01
      Ki: 0.001
      Kd: 0.01
      Ff: 0
static_power_global:
  x: 0
  y: 0
  z: -0.42
power_scale_factor: 1
thrusters:
  - name: bottom_front_left
    type: T200
    pos: [0.1905, 0.37465, -0.0381]
    rpy: [0, 90, 0]
    flipped: false
  - name: front_left
    type: T200
    pos: [0.3302, 0.358775, 0.0254]
    rpy: [0, 0, -45]
    flipped: true
  - name: front_right
    type: T200
    pos: [0.3302, -0.358775, 0.0254]
    rpy: [0, 0, 45]
    flipped: true
  - name: bottom_front_right
    type: T200
    pos: [0.1905, -0.37465, -0.0381]
    rpy: [0, 90, 0]
    flipped: false
  - name: bottom_back_left
    type: T200
    pos: [-0.1905, 0.37465, -0.0381]
    rpy: [0, 90, 0]
    flipped: false
  - name: back_left
    type: T200
    pos: [-0.3302, 0.358775, 0.0254]
    rpy: [0, 0, -135]
    flipped: true
  - name: bottom_back_right
    type: T200
    pos: [-0.1905, -0.37465, -0.0381]
    rpy: [0, 90, 0]
    flipped: false
  - name: back_right
    type: T200
    pos: [-0.3302, -0.358775, 0.0254]
    rpy: [0, 0, 135]
    flipped: true
wrench_matrix_file_path: data/oogway_wrench.csv
wrench_matrix_pinv_file_path: data/oogway_wrench_pinv.csv