# This service type contains data on changing servo angles

# The index of the servo to change (zero-indexed)
uint8 num

# The new angle of the servo
uint8 angle
---
# Indicates whether the new angle was successful
bool success
