[package]
name = "rustping"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.3.0"
hilbert_transform = "0.1.1"
num = "0.4.1"
num-traits = "0.2.17"
plotly = { version = "0.8.4", features = ["kaleido"] }
rayon = "1.8.1"
sci-rs = "0.3.8"
sdr = "0.7.0"
