[package]
name = "rustping"
version = "0.1.0"
edition = "2021"

#[lib]
#name = "spike"
#crate-type = ["cdylib"]

[dependencies]
csv = "1.3.0"
hilbert_transform = "0.1.1"
num = "0.4.1"
num-traits = "0.2.17"
plotly = { version = "0.8.4", features = ["kaleido"] }
plotpy = "0.5.1"
pyo3 = "0.20.3"
rayon = "1.8.1"
sci-rs = "0.3.8"
sdr = "0.7.0"
