# This servo contains data on changing servo angles

std_msgs/Header header

# The index of the servo to change (0-8 on current muliplexer) 
uint8 num 

# The new angle of the servo
uint16 angle
---

# Indicates whether the new angle was successful
bool success