# Goal

# The base filename of the data without the version
string filename

# Sampling frequency
uint32 samp_f

# Target frequency
uint32 tar_f

---
# Result

# Guess of the location of the pinger
geometry_msgs/Point guess

---
# Feedback

# Completed bandpass filtering
bool filtered

# Completed cross correlation
bool cross_correlated
