# Goal
string filename
string port
# Other Arduino parameters should be automatically detectable, if not, add them as parameters here.
---
# Result
bool success
---
# Feedback
int curr_stage
int total_stages
string message