name: build-without-docker

on:
  # Run this workflow when the docker subdirectory has not been modified
  push:
    branches:
      - master
    paths:
      - '!docker/**'
  pull_request:
    paths:
      - '!docker/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: [onboard, landside]
      fail-fast: false
    container: dukerobotics/robosub-ros:${{ matrix.workspace }}
    steps:
      - uses: actions/checkout@v2
      - name: Test build
        run: ./build.sh '${{ matrix.workspace }}'
